### ISSUE TITLE
Setstore fails ungracefully when address is not set

### ISSUE THREAD

**Issue by chrispanag** [kpapadatos/efoodgr#1]
```
Χρήστος @efood>  setstore
Getting stores for address undefined ...
(node:838) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'latitude' of undefined
    at Command.<anonymous> (/usr/lib/node_modules/efoodgr/dist/commands/setstore.js:26:35)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/efoodgr/dist/commands/setstore.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by kpapadatos** [comment]
I have my hands full at the moment but PR's are welcome! Also from your log, it seems the first name needs trimming.
